apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordscontainer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ordscontainer
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
