apiVersion: v1
kind: PersistentVolume
metadata:
  name: db19c-oracle-db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/test-pv"
