apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db19c-oracle-db
  labels:
    app.kubernetes.io/managed-by: Helm   
  annotations:
    meta.helm.sh/release-name: db19c
    meta.helm.sh/release-namespace: default      
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
