---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: davidgarciabeta/sqlcl-apex
  policy:
    semver:
      range: 1.0.x
