apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordscontainer
  labels:
    app: ordscontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordscontainer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordscontainer
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z sidb-sample 1521; do echo waiting for database; sleep 2; done;']
      containers:
      - image: ords:prueba
        imagePullPolicy: Never
        env:
        - name: HOSTNAME
          value: "sidb-sample"
        - name: DB_PORT
          value: "1521"
        - name: DB_SERVICE
          value: "ORCL1"
        - name: SYSDBA_USER
          value: "SYS"
        - name: SYSDBA_PASSWORD
          value: "oracle"    
        - name: ORDS_PASSWORD
          value: "oracle"
        name: ordscontainer
        ports:
        - containerPort: 8080
          name: ordscontainer
        resources:
          limits:
            memory: "1024Mi"
            cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
 name: ordscontainer
spec:
 type: LoadBalancer
 selector:
   app: ordscontainer
 ports:
   - name: client
     protocol: TCP
     port: 80
     targetPort: 8080
