apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordscontainer
  labels:
    app: ordscontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordscontainer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordscontainer
    spec:
      containers:
      - image: ords:prueba
        imagePullPolicy: Never
        env:
        - name: HOSTNAME
          value: "10.244.0.6"
        - name: DB_PORT
          value: "1521"
        - name: DB_SERVICE
          value: "ORCLCDB"
        - name: SYSDBA_USER
          value: "SYS"
        - name: SYSDBA_PASSWORD
          value: "oracle"    
        - name: ORDS_PASSWORD
          value: "oracle"
        name: ordscontainer
        ports:
        - containerPort: 8080
          name: ordscontainer
---
apiVersion: v1
kind: Service
metadata:
 name: ordscontainer
spec:
 type: LoadBalancer
 selector:
   app: ordscontainer
 ports:
   - name: client
     protocol: TCP
     port: 8080
     targetPort: 8080
