apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex
  namespace: argocd  
spec:    
  syncPolicy:
    syncOptions:
    - PruneLast=true
  project: default
  source:
    repoURL: https://github.com/gitdavidgarcia/K8S-APEX
    path: ords
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
