name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.USERNAME }}
       password: ${{ secrets.K8S }}

    - name: Build and push first Dockerfile
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ords/Dockerfile 
        push: true
        tags: davidgarciabeta/k8s-apex:1.0.1
    - name: Build and push second Dockerfile
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./liquibase/Dockerfile  # Ruta al segundo Dockerfile
        push: true
        tags: davidgarciabeta/sqlcl-apex:1.0.1
